org: yieldx
app: lambdas
service: lambdas

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: yieldx

functions:
  label_trolleys:
    handler: label_trolleys.default
    events:
      - http:
          method: get
          path: label-trolleys
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
                flock: true
                date: true
                rolling: true
                sourceWH: false
                destWH: false
                label1: true
                label2: false
                mqtt: false
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')",
                  "flock" : "$input.params('flock')",
                  "date" : "$input.params('date')",
                  "sourceWH" : "$input.params('sourceWH')",
                  "destWH" : "$input.params('destWH')",
                  "rolling" : "$input.params('rolling')",
                  "label1" : "$input.params('label1')",
                  "label2" : "$input.params('label2')",
                  "mqtt" : "$input.params('mqtt')"
                }

  check_user:
    handler: check_user.default
    events:
      - http:
          method: get
          path: check-user
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')"
                }

  get_flock_wh_date:
    handler: get_flock_wh_date.default
    events:
      - http:
          method: get
          path: get-flock-wh-date
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')"
                }
