org: yieldx
app: lambdas
service: lambdas

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: yieldx

functions:
  label_trolleys:
    handler: label_trolleys.default
    events:
      - http:
          method: get
          path: label-trolleys
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
                flock: true
                date: true
                wh: false
                label: true
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')",
                  "flock" : "$input.params('flock')",
                  "date" : "$input.params('date')",
                  "wh" : "$input.params('wh')",
                  "label" : "$input.params('label')"
                }

  check_user:
    handler: check_user.default
    events:
      - http:
          method: get
          path: check-user
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')"
                }

  get_flock_wh_date:
    handler: get_flock_wh_date.default
    events:
      - http:
          method: get
          path: get-flock-wh-date
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                db: true
            template:
              application/json: |
                { 
                  "db" : "$input.params('db')"
                }
